# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  API_TOKEN: $(AZURE_STATIC_WEB_APPS_FRONTEND_API_TOKEN)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# - script: |
#     npx depcheck
#   displayName: 'Check for unused or missing dependencies'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# - script: |
#     npm run dev
#   displayName: 'Run dev server'

- task: AzureStaticWebApp@0
  displayName: 'Deploy to Azure Web App'
  inputs:
    app_location: '/'
    api_location: ''      
    output_location: 'dist' 
    azure_static_web_apps_api_token: $(API_TOKEN)